### ISSUE TITLE
How does one access the request object?

### ISSUE THREAD

**Issue by et304383** [stackery/php-lambda-layer#20] opened 2019-01-14 18:30 UTC
No documentation on how to access the full request object in PHP. Like, the request type, the body, etc.

Can we please get a readme update explaining this?

**Comment by txase** [comment] 2019-01-15 22:06
You should be able to use standard PHP techniques to access the request data. For example, $_SERVER should be defined and provide info about the request: http://php.net/manual/en/reserved.variables.server.php.

I'm going to close this issue as the layer is working as intended and the reference PHP docs should provide all the documentation needed to use the language. Please reopen if you believe the layer isn't behaving correctly.

Thanks!

**Closed as completed by txase** 2019-01-15 22:06 UTC
